CREATE TABLE TBL_MEMBER(
   MEMBER_NAME VARCHAR2(1000),
   MEMBER_AGE NUMBER
);

DROP TABLE TBL_MEMBER;

/*
 * 자동차
 * 
 * - 자동차 번호
 * - 자동차 브랜드
 * - 출시 날짜
 * - 색상
 * - 가격
 * 
 * */

CREATE TABLE TBL_CAR(
   CAR_ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
   CAR_BRAND VARCHAR2(1000),
   CAR_RELEASE_DATE DATE,
   CAR_COLOR VARCHAR2(1000),
   CAR_PRICE NUMBER
);

ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(CAR_ID);

DROP TABLE TBL_CAR;

/*
 * 동물 테이블 생성
 * 
 * - 고유 번호
 * - 종류
 * - 나이
 * - 먹이
 * 
 * */

CREATE TABLE TBL_ANIMAL(
   ANIMAL_ID NUMBER,
   ANIMAL_TYPE VARCHAR2(1000),
   ANIMAL_AGE NUMBER,
   ANIMAL_EAT VARCHAR2(1000)
);

ALTER TABLE TBL_ANIMAL DROP CONSTRAINT PK_ANIMAL; 
ALTER TABLE TBL_ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY(ANIMAL_ID);

/*과제: 5개의 테이블 생성해보기*/

/* 화장품 테이블 형성 (테이블 이름 변경해보기)
 * - 화장품 고유 번호(PK)
 * - 화장품 종류
 * - 유통 기한
 * - 가격
 **/

CREATE TABLE TBL_COSMETIC(
	COSMETIC_ID NUMBER CONSTRAINT PK_COSMETIC PRIMARY KEY,
	COSMETIC_TYPE VARCHAR2(1000),
	COSMETIC_DATE DATE,
	COSMETIC_PRICE NUMBER
);

DROP TABLE TBL_COSMETIC;

ALTER TABLE TBL_COSMETIC RENAME TO TBL_COSMETICPRODUCT;


/* 노래방 테이블 형성
 * - 노래 번호 (PK)
 * - 노래 종류 (트로트, 발라드, ost ....)
 * - 노래 부른 가수
 * - 음원 발매일 (컬럼 삭제하기)
 * - 노래 인기 순위(새로운 컬럼으로 추가해보기)
 * */
CREATE TABLE TBL_SONG(
	SONG_ID NUMBER CONSTRAINT PK_SONG PRIMARY KEY,
	SONG_TYPE VARCHAR2(1000),
	SONG_SINGER VARCHAR2(1000),
	SONG_DATE DATE
);

ALTER TABLE TBL_SONG ADD(SONG_RANKING NUMBER);
ALTER TABLE TBL_SONG DROP COLUMN SONG_DATE;

/* 핸드폰 테이블 형성
 * - 핸드폰 고유 번호 (PK)
 * - 핸드폰 종류 (TYPE에서 BRAND로 이름 병경하기)
 * - 핸드폰 가격
 * - 핸드폰 용량 
 * */

CREATE TABLE TBL_PHONE(
	PHONE_NUMBER NUMBER CONSTRAINT PK_PHONE PRIMARY KEY,
	PHONE_TYPE VARCHAR2(1000),
	PHONE_PRICE NUMBER,
	PHONE_CAPACITY NUMBER
);

ALTER TABLE TBL_PHONE RENAME COLUMN PHONE_TYPE TO PHONE_BRAND;

/* 옷 테이블 형성
 * - 옷 번호 (PK)
 * - 옷 종류
 * - 옷 재고
 * - 옷 가격
 * - 옷 사이즈 (S,M,L)
 * */
CREATE TABLE TBL_CLOTHES(
	CLOTHES_NUMBER NUMBER,
	CLOTHES_TYPE VARCHAR2(300),
	CLOTHES_STOCK NUMBER,
	CLOTHES_PRICE NUMBER,
	CLOTHES_SIZE NUMBER
);

ALTER TABLE TBL_CLOTHES ADD CONSTRAINT PK_CLOTHES PRIMARY KEY(CLOTHES_NUMBER);
TRUNCATE TABLE TBL_CLOTHES;

/* 과일 테이블 형성
 * - 과일 품번
 * - 과일 이름
 * - 과일 당도
 * - 과일 가격
 * */

CREATE TABLE TBL_FRUIT(
	FRUIT_NUMBER NUMBER CONSTRAINT PK_FRUIT PRIMARY KEY,
	FRUIT_NAME VARCHAR2(301),
	FRUIT_BRIXDEGREE NUMBER,
	FRUIT_PRICE NUMBER
);